spring:
  config:
    import: "optional:classpath:api.properties"
  main:
    # Permite sobrescrever beans do Spring caso haja conflito de nomes (ex: customização de IA)
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 2048
    ollama:
      base-url: http://3.236.121.9:11434
      chat:
        options:
          model: llama3.1:8b
          temperature: 0.7

app:
  ai:
    provider: openai  # Valores possíveis: "openai" ou "ollama"
  tool:
    logging:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO