spring:
  config:
    import: "optional:classpath:api.properties"
  main:
    # Permite sobrescrever beans do Spring caso haja conflito de nomes (ex: customização de IA)
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 2048
    ollama:
      base-url: http://3.236.121.9:11434
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
          max-tokens: 2048

app:
  ai:
    provider: ollama  # Valores possíveis: "openai" ou "ollama"
  tool:
    logging:
      enabled: true

# Configurações de logging para debug
logging:
  level:
    root: INFO
    com.example.swaggeragent: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.boot.autoconfigure: DEBUG