spring:
  config:
    import: "optional:classpath:api.properties"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 2048
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL:qwen2.5:0.5b}
          temperature: 0.7

# Logging configuration
logging:
  level:
    root: INFO

app:
  tool:
    logging:
      enabled: true